### ISSUE TITLE
https://dbf.finalrewind.org/_Bhfname_.json lädt nicht

### ISSUE THREAD

**Issue by torowi** [derf/db-fakedisplay#12]
Der Titel sagt eigentlich schon alles: `https://dbf.finalrewind.org/_Bhfname_.json` lädt seit gestern Nachmittag nicht.
Bhfname ist dabei beliebig.

Es wird eine leere Seite gezeigt.

Firefox quittiert mit "content-encoding-Fehler".

Ist das so beabsichtigt oder vielleicht ein kleiner Fehler?

**Comment by derf** [comment]
Ist ein Fehler, der durch ein eigentlich harmloses Update des Webframeworks entstanden ist. Neuerdings werden Antworten dort standardmäßig komprimiert, was sich offenbar bei JSON mit einigen Clients beißt. Fix folgt gleich.
