### ISSUE TITLE
Zwei Bahnhöfe zusammen 

### ISSUE THREAD

**Issue by H999999** [derf/db-fakedisplay#15]
Bei der Abfahrtstafel Essen-Dellwig Ost wird auch Essen Dellwig angezeigt. Die beiden Haltepunkte sind dafür nah genug beieinander, aber haben beide ein Gleis 1. Hier wäre eine Unterscheidung nützlich. DB Produkte schreiben entweder klein den Bahnhofsnamen dazu oder zeigen nur einen von beiden an.

**Comment by derf** [comment]
Guter Punkt, das macht das IRIS-Backend nicht ganz optimal. Ich habe es gerade in https://github.com/derf/Travel-Status-DE-IRIS gefixt, das wird zeitnah in DBF einfließen.
