### ISSUE TITLE
502 Bad Gateway nginx

### ISSUE THREAD

**Issue by Intubun** [derf/db-fakedisplay#19]
Moin,
wenn die Seite geladen wird, dann kommt eine Fehlermeldung von nginx mit 502 Bad Gateway. Das soll so nicht, oder?
![image](https://github.com/user-attachments/assets/2ff1f098-4501-4115-8267-46e2e5c8072c)

**Comment by derf** [comment]
Nope :) war ein Fehler beim Deployment, läuft wieder.
