### ISSUE TITLE
Platform filtering doesn't work for EFA backend

### ISSUE THREAD

**Issue by NikTheDusky** [derf/db-fakedisplay#20]
I'm trying to build a physical departure board for my local bus and tram stop, but I ran into an issue when requesting departure times for specific platforms of a stop.

The problem is visible here: https://dbf.finalrewind.org/Heinrich-Heine-Allee?efa=VRR&rt=1&platforms=4
![image](https://github.com/user-attachments/assets/e4b45ee8-2749-43a9-9a7d-40492d3ae2e5)

When using the HAFAS backend, the filtering works properly: https://dbf.finalrewind.org/118036?hafas=AVV&rt=1&platforms=4
![image](https://github.com/user-attachments/assets/7f257720-640b-49f7-a02a-86f607e6fe14)

**Comment by derf** [comment]
Fixed, thanks for pointing it out!
