### ISSUE TITLE
Bitte neue (Haupt) Versionen als "Release" kennzeichnen.

### ISSUE THREAD

**Issue by pm-pm** [derf/db-fakedisplay#5]
Der Github Trigger "Watch Release" funktioniert und benachrichtigt nur, wenn eine neue Version als "Release" gekennzeichnet wird.
Ansonsten bekommt man diese Info nur wenn man "Watch (all)" eingestellt hat, dann erreichen einem aber auch andere Informationen.

Siehe z.B. hier: https://github.com/gotify/server/releases

**Comment by derf** [comment]
Not gonna happen, sorry.

GitHub ist nur einer von vielen Mirrors des Repositories und ich werde keine GitHub-spezifischen Aktionen bei Releases durchführen. Jedes Release ist getaggt; ich will doch hoffen dass sich damit eine passende Automatisierung einrichten lässt.
