### ISSUE TITLE
Eine leere "Datenschutzerklaerung" und "Impressum" Seite hinzufuegen

### ISSUE THREAD

**Issue by pm-pm** [derf/db-fakedisplay#6]
Wenn man das Fakedisplay auf einem eigenen Server installiert fuehren die Links zur Datenschutzerklaerung und zum Impressum auf einen 404.

Eine jeweils leere, aber existierende Seite wuerde den Fehler 404 vermeiden und man haette sofort den Anhaltspunkt wo man seine persoenlichen Informationen hinzufuegen kann.

**Comment by derf** [comment]
Das beißt sich mit dem "Git-Repository auschecken und direkt verwenden"-Workflow, da dann im Repository eingecheckte Dateien verändert werden müssen. Ich lege mal Beispielseiten unter `examples` ab.
